"""initial schema

Revision ID: 3656801b5262
Revises: 
Create Date: 2026-09-26 08:58:19.721787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('must_have', sa.JSON(), nullable=False),
    sa.Column('nice_to_have', sa.JSON(), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('resume_weight', sa.Float(), nullable=False),
    sa.Column('qa_weight', sa.Float(), nullable=False),
    sa.Column('pass_threshold', sa.Float(), nullable=False),
    sa.Column('hold_margin', sa.Float(), nullable=False),
    sa.Column('confidence_cutoff', sa.Float(), nullable=False),
    sa.Column('question_time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('candidates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('jd_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('education', sa.String(length=300), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('profile_type', sa.String(length=64), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resume_score', sa.Float(), nullable=True),
    sa.Column('resume_confidence', sa.Float(), nullable=True),
    sa.Column('qa_score', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('final_decision', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_jd_id'), ['jd_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidates_status'), ['status'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('jd_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('reference_answer', sa.Text(), nullable=False),
    sa.Column('rubric', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_jd_id'), ['jd_id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('candidate_id', sa.String(length=32), nullable=True),
    sa.Column('jd_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)

    op.create_table('candidate_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_status_history_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviews_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interviews_interviewer_id'), ['interviewer_id'], unique=False)

    op.create_table('next_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('next_steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_next_steps_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('resume_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('jd_id', sa.String(length=32), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('gaps', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('threshold_used', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resume_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resume_scores_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('screening_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('jd_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('current_question_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('qa_total', sa.Float(), nullable=True),
    sa.Column('qa_max', sa.Float(), nullable=True),
    sa.Column('qa_normalized', sa.Float(), nullable=True),
    sa.Column('combined_score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jd_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_screening_attempts_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('time_taken_sec', sa.Integer(), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('auto_submitted', sa.Boolean(), nullable=False),
    sa.Column('tab_switches', sa.Integer(), nullable=False),
    sa.Column('paste_count', sa.Integer(), nullable=False),
    sa.Column('copy_count', sa.Integer(), nullable=False),
    sa.Column('score_status', sa.String(length=16), nullable=False),
    sa.Column('score_error', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['screening_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_answer_attempt_question')
    )
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answers_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('interviewer_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=32), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interviewer_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interviewer_notes_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('answer_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rubric_hits', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer_scores')
    with op.batch_alter_table('interviewer_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviewer_notes_candidate_id'))

    op.drop_table('interviewer_notes')
    with op.batch_alter_table('answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answers_candidate_id'))
        batch_op.drop_index(batch_op.f('ix_answers_attempt_id'))

    op.drop_table('answers')
    with op.batch_alter_table('screening_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_attempts_candidate_id'))

    op.drop_table('screening_attempts')
    with op.batch_alter_table('resume_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resume_scores_candidate_id'))

    op.drop_table('resume_scores')
    with op.batch_alter_table('next_steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_next_steps_candidate_id'))

    op.drop_table('next_steps')
    with op.batch_alter_table('interviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interviews_interviewer_id'))
        batch_op.drop_index(batch_op.f('ix_interviews_candidate_id'))

    op.drop_table('interviews')
    with op.batch_alter_table('candidate_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_status_history_candidate_id'))

    op.drop_table('candidate_status_history')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_candidate_id'))
        batch_op.drop_index('ix_audit_created')

    op.drop_table('audit_logs')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_jd_id'))

    op.drop_table('questions')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_status'))
        batch_op.drop_index(batch_op.f('ix_candidates_jd_id'))

    op.drop_table('candidates')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
